### ISSUE TITLE
Glyph in TBitBtn

### ISSUE THREAD

**Issue by SoyYako** [EtheaDev/IconFontsImageList#23]
So, TButton have an "Images" property to get the images, but TBitBtn only have the "Glyph" property.

What is the way to add an icon from the TIconFontsImagesList to the "Glyph" property?

Best regards,

**Comment by carloBarazzetta** [comment]
Hi @SoyYako, TBitBtn and TSpeedButton are legacy controls and you should avoid using these in your applications, because it's not able to render an Icon with Alpha channel!
Look at this article, for example: https://www.bverhue.nl/delphisvg/2016/05/15/enable-transparency-with-tsvg2imagelist-on-vcl/
As you can see in the evolution of the project demo, I've substitute TBitBtn with TButton linked to the ImageList and setting ImageIndex or a TButton linked to an Action.
