### ISSUE TITLE
Some font is drawn incorrectly.

### ISSUE THREAD

**Issue by Davaamail** [EtheaDev/IconFontsImageList#38]
Hi. Thanks for your work, it was great, and solved some my problem.
There is some fixes... Some fonts other than Material Design and Segoe MDL2 drawn incorrectly. How to fix it.
![Untitled](https://user-images.githubusercontent.com/75078973/100354736-8c452200-302b-11eb-887b-c2cafafed658.png)

**Comment by carloBarazzetta** [comment]
Please send me the font and the info on the library you are using: it's VCL or FMX version?

**Comment by Davaamail** [comment]
Fontawesome, Weather Icons, etc.

**Comment by carloBarazzetta** [comment]
It appears to be an icon with different sizes from width and height - have you tried to set different width and height?

**Comment by Davaamail** [comment]
Let me send you an example that doesn't work. 
[Icon Font Example.zip](https://github.com/EtheaDev/IconFontsImageList/files/5605599/Icon.Font.Example.zip)

**Comment by carloBarazzetta** [comment]
The problem is the particular dimension of the icon fonts, that aren't in a square size and has an "offset".
The FMX version doesn't have separate width and height properties of the icons, so is not possible to adjust.
The VCL version has separate width and height sizes but the "offset" problem remains:
![image](https://user-images.githubusercontent.com/7803548/100425466-8da83600-308f-11eb-8eb3-6155686ade2b.png)
I need to investigate to find a solution to render font icons with those particular properties...
But I don't have many time, for now...

**Comment by Davaamail** [comment]
Ok. Thank you.

**Comment by carloBarazzetta** [comment]
Try with the latest 1.6.0 version for FMX to give me some feedback. You can specifiy different width and height and a zoom factor. I've tried with those icons settings W:64 H:48 and zoom 75%. I've changed also the component editor to add those functionality.

**Comment by carloBarazzetta** [comment]
using 1.6.1 FMX version you can play using Width Height and Zoom to adjust rendering of icons.
This is the example with weather icons at 80% zoom:
![image](https://user-images.githubusercontent.com/7803548/102504792-8fa75880-4081-11eb-85b8-763ca516baab.png)

**Comment by carloBarazzetta** [comment]
Here you can find your project updated that uses BitmapZoom=80% for IconFontImage component.
[Icon Fonts Example Updated.zip](https://github.com/EtheaDev/IconFontsImageList/files/5710288/Icon.Fonts.Example.Updated.zip)

**Comment by carloBarazzetta** [comment]
I suggest to use a Gliph instead of the IconFontImage component, as in the Demo Project...
